### ISSUE TITLE
The  controller.showInHand give me a blank map

### ISSUE THREAD

**Issue by Caranouga** [SBDPlugins/MapReflectionAPI#2]
As you told me on the issue I had opened on mapmanager. I used your fork, but I have 1 problem:

1) The functions controller.showInHand and controller.showInventory give me empty maps.

The code:
My inventory after the command: ![image](https://user-images.githubusercontent.com/62339171/177200963-1acfcd40-8a51-43f9-b817-672ad10e36ca.png)

2) The code I use to display the images in a frame gives me an error

The code: https://www.toptal.com/developers/hastebin/yipijezohe.java
The error: ```log
java.lang.NoSuchMethodException: net.minecraft.server.level.WorldServer.getEntity()
[19:21:14] [Server thread/WARN]: 	at java.base/java.lang.Class.getMethod(Class.java:2195)
[19:21:14] [Server thread/WARN]: 	at MapReflectionAPI-1.1.jar//tech.sbdevelopment.mapreflectionapi.utils.ReflectionUtil.callMethod(ReflectionUtil.java:283)
[19:21:14] [Server thread/WARN]: 	at MapReflectionAPI-1.1.jar//tech.sbdevelopment.mapreflectionapi.api.MapWrapper$1.getItemFrameById(MapWrapper.java:242)
[19:21:14] [Server thread/WARN]: 	at MapReflectionAPI-1.1.jar//tech.sbdevelopment.mapreflectionapi.api.MapWrapper$1.lambda$showInFrame$0(MapWrapper.java:219)
[19:21:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[19:21:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[19:21:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1567)
[19:21:14] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:490)
[19:21:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1483)
[19:21:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1282)
[19:21:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[19:21:14] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)```
The log: https://www.toptal.com/developers/hastebin/ahovexaloc.log

**Comment by stijnb1234** [comment]
Will check that.

**Comment by Caranouga** [comment]
I use minecraft 1.17.1 and paper ^^ I don't know if it's useful

**Comment by Caranouga** [comment]
If there is anything else I can do to help you let me know. If not, do you have a solution for one of the two problems. I also forgot to tell you, but for the 2nd problem where I have the error, the photo is displayed well in the frame, but it still gives me the error

**Comment by stijnb1234** [comment]
> If there is anything else I can do to help you let me know. If not, do you have a solution for one of the two problems. I also forgot to tell you, but for the 2nd problem where I have the error, the photo is displayed well in the frame, but it still gives me the error

It's just a fault in the reflection part. Will fix that asap.

**Comment by Caranouga** [comment]
Hello, do you have any news?

**Comment by stijnb1234** [comment]
> Hello, do you have any news?

Will start in a few hours with this issue and #4.

**Comment by Caranouga** [comment]
> > Hello, do you have any news?
> 
> Will start in a few hours with this issue and #4.

ok

**Comment by Caranouga** [comment]
Can you update the jar file on spigot and maven ?
