### ISSUE TITLE
Error on PlayerQuitEvent event

### ISSUE THREAD

**Issue by Timtendo12** [SBDPlugins/MapReflectionAPI#22]
Versie: `git-Purpur-2004 (MC: 1.20.1)*`

```java
[14:03:31 WARN]: java.lang.NoSuchFieldException: m
[14:03:31 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[14:03:31 WARN]:        at MapReflectionAPI-1.5.1 (1).jar//tech.sbdevelopment.mapreflectionapi.utils.ReflectionUtil.getDeclaredField(ReflectionUtil.java:378)
[14:03:31 WARN]:        at MapReflectionAPI-1.5.1 (1).jar//tech.sbdevelopment.mapreflectionapi.listeners.PacketListener.getChannel(PacketListener.java:147)
[14:03:31 WARN]:        at MapReflectionAPI-1.5.1 (1).jar//tech.sbdevelopment.mapreflectionapi.listeners.PacketListener.removePlayer(PacketListener.java:139)
[14:03:31 WARN]:        at MapReflectionAPI-1.5.1 (1).jar//tech.sbdevelopment.mapreflectionapi.listeners.PacketListener.onQuit(PacketListener.java:57)
[14:03:31 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor355.execute(Unknown Source)
[14:03:31 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[14:03:31 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[14:03:31 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:03:31 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[14:03:31 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[14:03:31 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[14:03:31 WARN]:        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:601)
[14:03:31 WARN]:        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:585)
[14:03:31 WARN]:        at net.minecraft.server.network.PlayerConnection.onDisconnect(PlayerConnection.java:2216)
[14:03:31 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2195)
[14:03:31 WARN]:        at net.minecraft.network.NetworkManager.m(NetworkManager.java:825)
[14:03:31 WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:254)
[14:03:31 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1614)
[14:03:31 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:487)
[14:03:31 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1421)
[14:03:31 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1192)
[14:03:31 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[14:03:31 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[14:03:31 ERROR]: Could not pass event PlayerQuitEvent to MapReflectionAPI v1.5.1
java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.eventLoop()" because "channel" is null
        at tech.sbdevelopment.mapreflectionapi.listeners.PacketListener.removePlayer(PacketListener.java:140) ~[MapReflectionAPI-1.5.1 (1).jar:?]
        at tech.sbdevelopment.mapreflectionapi.listeners.PacketListener.onQuit(PacketListener.java:57) ~[MapReflectionAPI-1.5.1 (1).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor355.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2004]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:601) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:585) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2216) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2195) ~[?:?]
        at net.minecraft.network.Connection.handleDisconnection(Connection.java:825) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:254) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1614) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1421) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2004]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
  ```

**Comment by stijnb1234** [comment]
Thanks for the report. Will check it out.

**Comment by StanByes** [comment]
Hey @stijnb1234 I've the same error, have you an idea of when are will you check for that please ?

**Comment by stijnb1234** [comment]
Version v1.5.2 fixes this issue, thanks @Timtendo12 and @StanByes for the report.

**Comment by StanByes** [comment]
Hello, I've a new issue with this plugin and ActionFoto :
`[13:30:35] [Server thread/WARN]: java.lang.NoSuchFieldException: ao
[13:30:35] [Server thread/WARN]:     at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[13:30:35] [Server thread/WARN]:     at MapReflectionAPI.jar//tech.sbdevelopment.mapreflectionapi.utils.ReflectionUtil.getDeclaredField(ReflectionUtil.java:366)
[13:30:35] [Server thread/WARN]:     at MapReflectionAPI.jar//tech.sbdevelopment.mapreflectionapi.api.MapWrapper$1.sendItemFramePacket(MapWrapper.java:337)
[13:30:35] [Server thread/WARN]:     at MapReflectionAPI.jar//tech.sbdevelopment.mapreflectionapi.api.MapWrapper$1.lambda$showInFrame$0(MapWrapper.java:262)
[13:30:35] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101)
[13:30:35] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480)
[13:30:35] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1480)
[13:30:35] [Server thread/WARN]:     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[13:30:35] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1394)
[13:30:35] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1171)
[13:30:35] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[13:30:35] [Server thread/WARN]:     at java.base/java.lang.Thread.run(Thread.java:833)
[13:30:35] [Server thread/WARN]: [MapReflectionAPI] Task #373911 for MapReflectionAPI v1.5.2 generated an exception
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "dataWatcherObject" is null
    at tech.sbdevelopment.mapreflectionapi.api.MapWrapper$1.sendItemFramePacket(MapWrapper.java:347) ~[MapReflectionAPI.jar:?]
    at tech.sbdevelopment.mapreflectionapi.api.MapWrapper$1.lambda$showInFrame$0(MapWrapper.java:262) ~[MapReflectionAPI.jar:?]
    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-108]
    at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-108]
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-108]
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-108]
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-108]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-108]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-108]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by Timtendo12** [comment]
> Hello, I've a new issue with this plugin and ActionFoto : `[13:30:35] [Server thread/WARN]: java.lang.NoSuchFieldException: ao [13:30:35] [Server thread/WARN]: at java.base/java.lang.Class.getDeclaredField(Class.java:2610) [13:30:35] [Server thread/WARN]: at MapReflectionAPI.jar//tech.sbdevelopment.mapreflectionapi.utils.ReflectionUtil.getDeclaredField(ReflectionUtil.java:366) [13:30:35] [Server thread/WARN]: at MapReflectionAPI.jar//tech.sbdevelopment.mapreflectionapi.api.MapWrapper$1.sendItemFramePacket(MapWrapper.java:337) [13:30:35] [Server thread/WARN]: at MapReflectionAPI.jar//tech.sbdevelopment.mapreflectionapi.api.MapWrapper$1.lambda$showInFrame$0(MapWrapper.java:262) [13:30:35] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) [13:30:35] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) [13:30:35] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1480) [13:30:35] [Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447) [13:30:35] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1394) [13:30:35] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1171) [13:30:35] [Server thread/WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) [13:30:35] [Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:833) [13:30:35] [Server thread/WARN]: [MapReflectionAPI] Task #373911 for MapReflectionAPI v1.5.2 generated an exception java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "dataWatcherObject" is null at tech.sbdevelopment.mapreflectionapi.api.MapWrapper$1.sendItemFramePacket(MapWrapper.java:347) ~[MapReflectionAPI.jar:?] at tech.sbdevelopment.mapreflectionapi.api.MapWrapper$1.lambda$showInFrame$0(MapWrapper.java:262) ~[MapReflectionAPI.jar:?] at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-108] at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-108] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-108] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-108] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-108] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-108] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-108] at java.lang.Thread.run(Thread.java:833) ~[?:?]`

I think its best if you create a new issue for this error since this error is already closed

**Comment by StanByes** [comment]
Yes I'll open a new issue
