### ISSUE TITLE
NoSuchFieldException 1.20.1

### ISSUE THREAD

**Issue by StanByes** [SBDPlugins/MapReflectionAPI#23]
Hello I tried to use MapReflectionAPI with ActionFoto in 1.20.1 and I got that error when I try to take a picture :
`[13:30:35] [Server thread/WARN]: java.lang.NoSuchFieldException: ao 
[13:30:35] [Server thread/WARN]:     at java.base/java.lang.Class.getDeclaredField(Class.java:2610) 
[13:30:35] [Server thread/WARN]:     at MapReflectionAPI.jar//tech.sbdevelopment.mapreflectionapi.utils.ReflectionUtil.getDeclaredField(ReflectionUtil.java:366) 
[13:30:35] [Server thread/WARN]:     at MapReflectionAPI.jar//tech.sbdevelopment.mapreflectionapi.api.MapWrapper$1.sendItemFramePacket(MapWrapper.java:337) [13:30:35] [Server thread/WARN]:     at MapReflectionAPI.jar//tech.sbdevelopment.mapreflectionapi.api.MapWrapper$1.lambda$showInFrame$0(MapWrapper.java:262) [13:30:35] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) 
[13:30:35] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) 
[13:30:35] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1480) 
[13:30:35] [Server thread/WARN]:     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447) 
[13:30:35] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1394) 
[13:30:35] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1171) 
[13:30:35] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) 
[13:30:35] [Server thread/WARN]:     at java.base/java.lang.Thread.run(Thread.java:833) 
[13:30:35] [Server thread/WARN]: [MapReflectionAPI] Task #373911 for MapReflectionAPI v1.5.2 generated an exception java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "dataWatcherObject" is null at tech.sbdevelopment.mapreflectionapi.api.MapWrapper$1.sendItemFramePacket(MapWrapper.java:347) ~[MapReflectionAPI.jar:?] at tech.sbdevelopment.mapreflectionapi.api.MapWrapper$1.lambda$showInFrame$0(MapWrapper.java:262) ~[MapReflectionAPI.jar:?] at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-108] at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-108] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-108] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-108] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-108] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-108] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-108] at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by stijnb1234** [comment]
Fixed in v1.6
