### ISSUE TITLE
1.20.2 support issues

### ISSUE THREAD

**Issue by StanByes** [SBDPlugins/MapReflectionAPI#24]
I got that error when I tried to access to my server and disconnect before connection ending to the server :
```
[09:31:42] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to MapReflectionAPI v1.6
java.util.NoSuchElementException: packet_handler
    at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
    at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
    at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
    at tech.sbdevelopment.mapreflectionapi.listeners.PacketListener.injectPlayer(PacketListener.java:135) ~[MapReflectionAPI.jar:?]
    at tech.sbdevelopment.mapreflectionapi.listeners.PacketListener.onJoin(PacketListener.java:52) ~[MapReflectionAPI.jar:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor285.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-108]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
    at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-108]
    at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-108]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
    at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:339) ~[paper-1.20.1.jar:git-Paper-108]
    at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
    at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
    at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
    at net.minecraft.network.Connection.tick(Connection.java:602) ~[?:?]
    at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1587) ~[paper-1.20.1.jar:git-Paper-108]
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-108]
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-108]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-108]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-108]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
    ```

**Comment by StanByes** [comment]
I forgot to tell I'm in 1.20.1

**Comment by stijnb1234** [comment]
@StanByes Try if it works now, if not, please let me know.

**Comment by StanByes** [comment]
Hello @stijnb1234
I've turned my server to 1.20.2 and use the last version you have pushed recently and I've this issue now :
```
[19:06:29] [Server thread/WARN]: java.lang.NoSuchFieldException: n
[19:06:29] [Server thread/WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[19:06:29] [Server thread/WARN]: 	at MapReflectionAPI.jar//tech.sbdevelopment.mapreflectionapi.utils.ReflectionUtil.getDeclaredField(ReflectionUtil.java:291)
[19:06:29] [Server thread/WARN]: 	at MapReflectionAPI.jar//tech.sbdevelopment.mapreflectionapi.listeners.PacketListener.getChannel(PacketListener.java:148)
[19:06:29] [Server thread/WARN]: 	at MapReflectionAPI.jar//tech.sbdevelopment.mapreflectionapi.listeners.PacketListener.injectPlayer(PacketListener.java:135)
[19:06:29] [Server thread/WARN]: 	at MapReflectionAPI.jar//tech.sbdevelopment.mapreflectionapi.listeners.PacketListener.onJoin(PacketListener.java:53)
[19:06:29] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor94.execute(Unknown Source)
[19:06:29] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[19:06:29] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[19:06:29] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:06:29] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[19:06:29] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[19:06:29] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[19:06:29] [Server thread/WARN]: 	at net.minecraft.server.players.PlayerList.a(PlayerList.java:325)
[19:06:29] [Server thread/WARN]: 	at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.a(ServerConfigurationPacketListenerImpl.java:130)
[19:06:29] [Server thread/WARN]: 	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:18)
[19:06:29] [Server thread/WARN]: 	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9)
[19:06:29] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:53)
[19:06:29] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[19:06:29] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[19:06:29] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[19:06:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324)
[19:06:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[19:06:29] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[19:06:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1301)
[19:06:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1294)
[19:06:29] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[19:06:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1371)
[19:06:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1156)
[19:06:29] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[19:06:29] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[19:06:29] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to MapReflectionAPI v1.6.1
java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.pipeline()" because "channel" is null
	at tech.sbdevelopment.mapreflectionapi.listeners.PacketListener.injectPlayer(PacketListener.java:136) ~[MapReflectionAPI.jar:?]
	at tech.sbdevelopment.mapreflectionapi.listeners.PacketListener.onJoin(PacketListener.java:53) ~[MapReflectionAPI.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor94.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-243]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-243]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-243]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:325) ~[paper-1.20.2.jar:git-Paper-243]
	at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:130) ~[paper-1.20.2.jar:git-Paper-243]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:18) ~[paper-1.20.2.jar:git-Paper-243]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9) ~[paper-1.20.2.jar:git-Paper-243]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-243]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-243]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-243]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-243]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-243]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1371) ~[paper-1.20.2.jar:git-Paper-243]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-243]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-243]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by stijnb1234** [comment]
Thanks for letting me know. Will check it out and update you ;)

**Comment by StanByes** [comment]
Thanks 💯

**Comment by StanByes** [comment]
I'll looking to make a Pull Request in few hours if I find a solution

**Comment by StanByes** [comment]
Update : Issue found, I'm testing a patch

**Comment by StanByes** [comment]
The patch is good, I'll create a PR now
