### ISSUE TITLE
NoSuchMethodException 1.20.2

### ISSUE THREAD

**Issue by erenkarakal** [SBDPlugins/MapReflectionAPI#26]
During startup:
```
java.lang.NoSuchMethodException: no such method: net.minecraft.server.network.PlayerConnection.a(Packet)void/invokeVirtual
 	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:976)
 	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1117)
 	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3649)
 	at java.base/java.lang.invoke.MethodHandles$Lookup.findVirtual(MethodHandles.java:2680)
 	at MapReflectionAPI-1.6.jar//tech.sbdevelopment.mapreflectionapi.utils.ReflectionUtil.<clinit>(ReflectionUtil.java:151)
 	at MapReflectionAPI-1.6.jar//tech.sbdevelopment.mapreflectionapi.MapReflectionAPI.onEnable(MapReflectionAPI.java:70)
 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
 	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644)
 	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555)
 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627)
 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424)
 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1086)
 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
 	at java.base/java.lang.Thread.run(Thread.java:833)
 Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.server.network.PlayerConnection.a(net.minecraft.network.protocol.Packet)'
 	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
 	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1085)
 	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1114)
 	... 16 more
```

**Comment by stijnb1234** [comment]
No 1.20.2 support yet, I'm working on it.

**Comment by stijnb1234** [comment]
Added in v1.6.1
