### ISSUE TITLE
Possible 1.19.2 support issues

### ISSUE THREAD

**Issue by stijnb1234** [SBDPlugins/MapReflectionAPI#27]
```
22.10 16:13:06 [Server] WARN java.lang.ClassNotFoundException: net.minecraft.network.syncher.DataWatcher$b
22.10 16:13:06 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
22.10 16:13:06 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
22.10 16:13:06 [Server] WARN at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
22.10 16:13:06 [Server] WARN at java.base/java.lang.Class.forName0(Native Method)
22.10 16:13:06 [Server] WARN at java.base/java.lang.Class.forName(Class.java:375)
22.10 16:13:06 [Server] WARN at MapReflectionAPI-1.6.1.jar//tech.sbdevelopment.mapreflectionapi.utils.ReflectionUtils.getNMSClass(ReflectionUtils.java:349)
22.10 16:13:06 [Server] WARN at MapReflectionAPI-1.6.1.jar//tech.sbdevelopment.mapreflectionapi.api.MapWrapper$1.sendItemFramePacket(MapWrapper.java:348)
22.10 16:13:06 [Server] WARN at MapReflectionAPI-1.6.1.jar//tech.sbdevelopment.mapreflectionapi.api.MapWrapper$1.lambda$showInFrame$0(MapWrapper.java:265)
22.10 16:13:06 [Server] WARN at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
22.10 16:13:06 [Server] WARN at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
22.10 16:13:06 [Server] WARN at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1493)
22.10 16:13:06 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
22.10 16:13:06 [Server] WARN at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1417)
22.10 16:13:06 [Server] WARN at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1193)
22.10 16:13:06 [Server] WARN at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
22.10 16:13:06 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
22.10 16:13:06 [Server] WARN [MapReflectionAPI] Task #125247 for MapReflectionAPI v1.6.1 generated an exception
22.10 16:13:06 [Server] INFO java.lang.NullPointerException: Cannot invoke "java.lang.Class.getMethod(String, java.lang.Class[])" because "dataWatcherRecordClass" is null
22.10 16:13:06 [Server] INFO at tech.sbdevelopment.mapreflectionapi.api.MapWrapper$1.sendItemFramePacket(MapWrapper.java:352) ~[MapReflectionAPI-1.6.1.jar:?]
22.10 16:13:06 [Server] INFO at tech.sbdevelopment.mapreflectionapi.api.MapWrapper$1.lambda$showInFrame$0(MapWrapper.java:265) ~[MapReflectionAPI-1.6.1.jar:?]
22.10 16:13:06 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-135]
22.10 16:13:06 [Server] INFO at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-135]
22.10 16:13:06 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1493) ~[paper-1.19.2.jar:git-Paper-135]
22.10 16:13:06 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-135]
22.10 16:13:06 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1417) ~[paper-1.19.2.jar:git-Paper-135]
22.10 16:13:06 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1193) ~[paper-1.19.2.jar:git-Paper-135]
22.10 16:13:06 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-135]
```

**Comment by stijnb1234** [comment]
Fixed in v1.6.2
