### ISSUE TITLE
NoSuchFieldException:n [PaperMC 1.20.6]

### ISSUE THREAD

**Issue by Ym64** [SBDPlugins/MapReflectionAPI#35]
Plugin seems to have a few errors in version 1.20.6.

```
[15:52:16 WARN]: java.lang.NoSuchFieldException: n
[15:52:16 WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2782)
[15:52:16 WARN]: 	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90)
[15:52:16 WARN]: 	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source)
[15:52:16 WARN]: 	at MapReflectionAPI-1.6.4.jar//tech.sbdevelopment.mapreflectionapi.utils.ReflectionUtil.getDeclaredField(ReflectionUtil.java:323)
[15:52:16 WARN]: 	at MapReflectionAPI-1.6.4.jar//tech.sbdevelopment.mapreflectionapi.listeners.PacketListener.getChannel(PacketListener.java:203)
[15:52:16 WARN]: 	at MapReflectionAPI-1.6.4.jar//tech.sbdevelopment.mapreflectionapi.listeners.PacketListener.injectPlayer(PacketListener.java:192)
[15:52:16 WARN]: 	at MapReflectionAPI-1.6.4.jar//tech.sbdevelopment.mapreflectionapi.listeners.PacketListener.onJoin(PacketListener.java:68)
[15:52:16 WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor4.execute(Unknown Source)
[15:52:16 WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[15:52:16 WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[15:52:16 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[15:52:16 WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[15:52:16 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[15:52:16 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[15:52:16 WARN]: 	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347)
[15:52:16 WARN]: 	at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:153)
[15:52:16 WARN]: 	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22)
[15:52:16 WARN]: 	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13)
[15:52:16 WARN]: 	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55)
[15:52:16 WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[15:52:16 WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[15:52:16 WARN]: 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[15:52:16 WARN]: 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511)
[15:52:16 WARN]: 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195)
[15:52:16 WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[15:52:16 WARN]: 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488)
[15:52:16 WARN]: 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411)
[15:52:16 WARN]: 	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[15:52:16 WARN]: 	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377)
[15:52:16 WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238)
[15:52:16 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[15:52:16 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by Ym64** [comment]
This error comes right after (and gets sent on PlayerJoinEvent):
```
[15:52:16 ERROR]: Could not pass event PlayerJoinEvent to MapReflectionAPI v1.6.4
java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.pipeline()" because "channel" is null
	at MapReflectionAPI-1.6.4.jar/tech.sbdevelopment.mapreflectionapi.listeners.PacketListener.injectPlayer(PacketListener.java:193) ~[MapReflectionAPI-1.6.4.jar:?]
	at MapReflectionAPI-1.6.4.jar/tech.sbdevelopment.mapreflectionapi.listeners.PacketListener.onJoin(PacketListener.java:68) ~[MapReflectionAPI-1.6.4.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor4.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-149-6e71f41]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
	at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:153) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
	at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-149-6e71f41]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by stijnb1234** [comment]
Should be resolved, if not let me know.
